<?php

namespace App\Services;

use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

/**
 * Stores and removes the company letterhead logo.
 *
 * Mirrors StaffPhotoService: the storage decision — disk, directory, what
 * happens to the file being replaced — lives here rather than in the
 * controller, so it can be swapped for S3 without touching HTTP code.
 */
class CompanyLogoService
{
    public const DISK = 'public';

    public const DIRECTORY = 'company-logo';

    /**
     * Store a new logo and delete the one it replaces.
     *
     * The filename is generated by Laravel rather than taken from the
     * upload, so a hostile name cannot traverse directories or collide.
     */
    public function store(UploadedFile $file, ?string $replacing = null): string
    {
        $path = $file->store(self::DIRECTORY, self::DISK);

        if ($replacing) {
            $this->delete($replacing);
        }

        return $path;
    }

    public function delete(?string $path): void
    {
        if (blank($path)) {
            return;
        }

        Storage::disk(self::DISK)->delete($path);
    }

    /**
     * Public URL for the stored logo, or null when there is none.
     */
    public function url(?string $path): ?string
    {
        if (blank($path) || ! Storage::disk(self::DISK)->exists($path)) {
            return null;
        }

        $url = Storage::disk(self::DISK)->url($path);

        // See StaffPhotoService::url() — reduces to a root-relative path on
        // the local disk so it resolves regardless of which host/port
        // actually served the page.
        if (config('filesystems.disks.'.self::DISK.'.driver') === 'local') {
            return parse_url($url, PHP_URL_PATH) ?: $url;
        }

        return $url;
    }

    /**
     * Absolute filesystem path for the stored logo, or null when there is
     * none. The PDF template needs this to inline the logo as a data URI —
     * dompdf cannot reliably fetch it over HTTP.
     */
    public function absolutePath(?string $path): ?string
    {
        if (blank($path) || ! Storage::disk(self::DISK)->exists($path)) {
            return null;
        }

        return Storage::disk(self::DISK)->path($path);
    }
}
