<?php

namespace App\Services;

use App\Models\User;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

/**
 * Stores and removes staff profile photos.
 *
 * Isolated from the controller so the storage decision — which disk, which
 * directory, what happens to the previous file — lives in one place and can
 * be swapped for S3 without touching HTTP code.
 */
class StaffPhotoService
{
    public const DISK = 'public';

    public const DIRECTORY = 'staff-photos';

    /**
     * Store a new photo and delete the one it replaces.
     *
     * The filename is generated by Laravel rather than taken from the upload,
     * so a hostile name cannot traverse directories or collide.
     */
    public function store(UploadedFile $file, ?string $replacing = null): string
    {
        $path = $file->store(self::DIRECTORY, self::DISK);

        if ($replacing) {
            $this->delete($replacing);
        }

        return $path;
    }

    public function delete(?string $path): void
    {
        if (blank($path)) {
            return;
        }

        Storage::disk(self::DISK)->delete($path);
    }

    /**
     * Public URL for a stored photo, or null when there is none.
     *
     * Returns null rather than a broken URL if the file is missing, so the
     * view falls back to initials instead of a broken image icon.
     */
    public function url(?string $path): ?string
    {
        if (blank($path) || ! Storage::disk(self::DISK)->exists($path)) {
            return null;
        }

        $url = Storage::disk(self::DISK)->url($path);

        /*
         * The local disk prefixes APP_URL, so with APP_URL=http://localhost
         * every photo points at port 80 even while the app is being browsed
         * on `php artisan serve` at 127.0.0.1:8000 — the image 404s and the
         * upload looks broken. Reducing it to a root-relative path makes it
         * resolve against whatever host actually served the page.
         *
         * Remote drivers (S3 and friends) must keep their absolute URL.
         */
        if (config('filesystems.disks.'.self::DISK.'.driver') === 'local') {
            return parse_url($url, PHP_URL_PATH) ?: $url;
        }

        return $url;
    }

    /**
     * Remove a staff member's photo and clear the column.
     */
    public function purgeFor(User $staff): void
    {
        $this->delete($staff->photo);

        $staff->forceFill(['photo' => null])->saveQuietly();
    }
}
